language: go
sudo: false

os:
  - osx

go:
  - 1.8
  - tip

before_install:
  - go get -v github.com/garyburd/redigo/redis
  - go get -v github.com/stretchr/testify/assert
  - brew update
  - brew install redis

before_script:
  - redis-server &

script:
  - go test

