language: go
sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

services:
  - redis-server

before_install:
  - go get -v github.com/garyburd/redigo/redis
  - go get -v github.com/stretchr/testify/assert

script:
  - go test

